/*
 * @Descripttion:
 * @version:
 * @Author: Fir
 * @Date: 2022-12-07 13:04:15
 * @LastEditors: Fir
 * @LastEditTime: 2022-12-07 19:29:07
 */
#include <stdio.h>

int main()
{
    int n;
    int cnt = 1;
    scanf("%d", &n);
    printf("Hailstone generated by %d:\n", n);
    printf("%4d", n);
    while (n != 1)
    {
        if (n & 1)
        {
            // printf("%4d",3*n+1);
            n = 3 * n + 1;
        }
        else
        {
            n = n >> 1;
        }
        printf("%4d", n);
        if (++cnt % 6 == 0)
        {
            printf("\n");
            // cnt=6;
        }
    }
    if (cnt % 6 != 0)
        printf("\n");
    printf("Number of hailstone generated:%d", cnt);
    return 0;
}